### ISSUE TITLE
Crash when using batch texture export

### ISSUE THREAD

**Issue by DoubtForge** [ermaccer/SSFExplorer#1]
Hello, ermaccer
The tool crashes when trying to batch export textures, in any of three modes, from, in my case, shujinko_13.ssf

**Comment by ermaccer** [comment]
I assume you are trying to export textures from shujinko_13.ssf, and not the archives inside it. 
Extract 0.dat/1.dat (if mku), open it, and then extract textures.

Thanks for the report though, I'll look into why "no textures" doesnt show up.

**Comment by DoubtForge** [comment]
That was indeed the case

**Comment by ermaccer** [comment]
"Fixed" mass exporting from SSFs.
